name: CI/CD - Wisecow -> Local Minikube (self-hosted)

on:
  push:
    branches: [ "main" ]

env:
  # DockerHub repo (from GitHub Secrets)
  IMAGE_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/wisecow

  # Kubernetes deployment details (static values, not secrets)
  K8S_NAMESPACE: wisecow
  DEPLOYMENT_NAME: wisecow 

jobs:
  build-and-deploy:
    runs-on: self-hosted   # 👈 will use your local runner (must be online)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_REPO }}:latest
            ${{ env.IMAGE_REPO }}:${{ github.sha }}

      - name: Deploy to Minikube
        shell: bash 
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Updating deployment image to $IMAGE_REPO:$IMAGE_TAG"
          kubectl config current-context
          kubectl -n $K8S_NAMESPACE set image deployment/$DEPLOYMENT_NAME \
            $DEPLOYMENT_NAME=$IMAGE_REPO:$IMAGE_TAG --record
          kubectl -n $K8S_NAMESPACE rollout status deployment/$DEPLOYMENT_NAME --timeout=120s
